### ISSUE TITLE
COS - Add a recap when you "finish" one side of a screen

### ISSUE THREAD

**Issue by greatbacon** [feltcoop/felt#39]
Currently if you go through one or the other of a given side of an onboarding screen (un- or consentful (c8l?)) it just advances to the next screen. Instead when you complete a side of the screen it should give you a popup summing up what you just went through in the screen.

~~A user should also have to complete both sides of a given screen to advance.~~ done in #53

**Comment by ryanatkn** [comment]
Both sides have to be complete to advanced with PR #53. Currently, when the second completes, it instantly goes to the next screen.

Two possible changes:

- visual indication when the second completes (with a pause or animation), to make it more obvious that "you've finished both sides"
- recap information, requiring a click to continue

**Comment by greatbacon** [comment]
On second thought, is it maybe too pedantic to have a recap pop up every time they finish a section? I think when I originally wrote this I had a single recap in mind after finishing both sides of screen.

**Comment by ryanatkn** [comment]
Guessing game :game_die:

**Comment by ryanatkn** [comment]
I'm thinking of keeping this minimal -- it'll ask you to guess which is which, and display a correct/incorrect status, but won't track or display any additional information.

**Comment by greatbacon** [comment]
Maybe as a follow on issue, we could add a more "consentful" version where it asks users before they start

1.) Would you like to be quizzed?
1.) Would you like to be scored?

But I think a light touch to start with is a great call

**Comment by ryanatkn** [comment]
Instead of giving any choices, the current implementation presents the guessing buttons, and when one is clicked, replaces both with a single button, taking up the same space, to proceed, so the user can effectively just double click to ignore the prompts.

The prompt also includes the summary text for the current affirmative consent principle, making the learning experience a little nicer for those who are interested, compared to just rendering the text at the top of every screen.
