### ISSUE TITLE
COS - Implement `Consentful-Unburdensome` page

### ISSUE THREAD

**Issue by greatbacon** [feltcoop/felt#43]
Please see product brief for more details.

**Comment by ryanatkn** [comment]
Hah so GitHub's automatic issue closing is normally great - that's why I put "fix #N" in commit messages - but it saw this in my PR and closed this issue:

`addresses but doesn't necessarily close #43`

Surprised me because I didn't know it parsed PR text --

![sccreen](https://user-images.githubusercontent.com/2608646/120937135-f7516e80-c6c8-11eb-84fc-425e1054aa4f.png)
ext content (not just commit messages), and funnily it's parsing a sentence where I explicitly say it *does not* close the issue.
